name = "Phlogiston"
license = "MIT"
licenselink = "https://github.com/RedMike/phlogiston/blob/master/LICENSE.md"
description = "Phlogiston is a simple website template built for portfolio/blog websites. Its main goal is to provide a good base to start off from for user modifications that correspond to your own use cases."
homepage = "https://github.com/RedMike/phlogiston"
tags = ["blog", "simple", "minimal", "responsive"]
features = ["blog", "disqus", "responsive"]
min_version = 0.19

[author]
  name = "Mike Roibu"
  homepage = "https://codingden.net"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""