baseURL = "https://example.com/"
languageCode = "en-us"
title = "Sample Site"
theme = "phlogiston"

[Params]
Image120 = "//gravatar.com/avatar/abc?s=120"
Image240 = "//gravatar.com/avatar/abc?s=240"
Description = """Add a description here about yourself, your projects, or your page. You can even add a whole load of text so it ends up splitting across multiple lines like this. Of course too many makes it look a bit busy, so don't go overboard.

Add multiple paragraphs, or even a list:

* Like
* This
* Or a [link](http://google.com) even
"""
Navbar = true
NavbarCategories = ["post", "project"]
FrontPageCategories = ["post"]

[[Params.socialIcons]]
  iconClass = "fa fa-github-square"
  url = "https://github.com/Example"

[[Params.socialIcons]]
  iconClass = "fa fa-twitter-square"
  url = "https://twitter.com/Example"

[[Params.socialIcons]]
  iconClass = "fa fa-youtube-square"
  url = "https://www.youtube.com/channel/abc"

[[Params.customJs]]
  url = "https://use.fontawesome.com/5091388bd8.js"