baseURL = "https://codingden.net/"
languageCode = "en-us"
title = "Sample Site"
theme = "phlogiston"
disqusShortname = "coding-den"

[Params]
Image120 = "//gravatar.com/avatar/f2ee31373b0bafccc33548db4a5f42db?s=120"
Image240 = "//gravatar.com/avatar/f2ee31373b0bafccc33548db4a5f42db?s=240"
Description = """Add a description here about yourself, your projects, or your page. You can even add a whole load of text so it ends up splitting across multiple lines like this. Of course too many makes it look a bit busy, so don't go overboard.

Add multiple paragraphs, or even a list:

* Like
* This
* Or a [link](http://google.com) even
"""
Navbar = true
NavbarCategories = ["post", "project"]
FrontPageCategories = ["post"]
GoogleAnalyticsCode = "UA-100000000-1"

[[Params.socialIcons]]
  iconClass = "fa fa-github-square"
  url = "https://github.com/RedMike"

[[Params.socialIcons]]
  iconClass = "fa fa-twitter-square"
  url = "https://twitter.com/MikeRedhorse"

[[Params.socialIcons]]
  iconClass = "fa fa-youtube-square"
  url = "https://www.youtube.com/channel/UCf-SN9h5_sEC0EF9KTWZFKw"

[[Params.customJs]]
  url = "https://use.fontawesome.com/5091388bd8.js"

[[Params.customJs]]
  url = "/js/temp.js"

[[Params.customCss]]
  url = "/css/custom.css"